import { Question, QuestionType } from './types';

const cleanUrl = (url?: string): string | undefined => {
    if (!url) return undefined;
    return url.trim()
        .replace(/\s+/g, '')
        .replace(/res\.ioe\.vnzedu/, 'res.ioe.vn/edu')
        .replace(/res\.ioe\.vii/, 'res.ioe.vn')
        .replace(/res\.ioe\.vm/, 'res.ioe.vn')
        .replace(/Audio\s*mp3/i, 'Audio.mp3')
        .replace(/ImageExam\s*(\d)/, 'ImageExam/$1')
        .replace(/Olympic\s*ExamData/, 'OlympicExamData')
        .replace(/EOlympic\s*ExamData/, 'EOlympic/ExamData')
        .replace(/'/g, '')
        .replace(/Audio-mp3/i, 'Audio.mp3');
};

export const QUIZ_DATA: Question[] = [
  { id: 1, type: QuestionType.FILL_IN_BLANK, questionText: "What’s y_ ur name?", correctAnswer: "o", explanation: "Your: Của bạn." },
  { id: 2, type: QuestionType.FILL_IN_BLANK, questionText: "Let’s go to the school _ _ _ _ _ _ _ .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206306167591442_Audio.mp3"), correctAnswer: "library", explanation: "School library: Thư viện trường học." },
  { id: 3, type: QuestionType.FILL_IN_BLANK, questionText: "I draw a pictu_ _ in the room.", correctAnswer: "re", explanation: "Picture: Bức tranh." },
  { id: 4, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ at is your name? - My name is Hung.", correctAnswer: "Wh", explanation: "What: Cái gì/Gì." },
  { id: 5, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["your book,", "Open", "please!"], correctAnswer: "Open your book, please!", explanation: "Làm ơn mở sách ra." },
  { id: 6, type: QuestionType.MULTIPLE_CHOICE, questionText: "May I ___ the book?", options: ["open", "stand", "play", "sit"], correctAnswer: "open", explanation: "Open the book: Mở sách." },
  { id: 7, type: QuestionType.FILL_IN_BLANK, questionText: "That is a big tr...e.", options: ["a", "u", "e", "i"], correctAnswer: "e", explanation: "Tree: Cái cây." },
  { id: 8, type: QuestionType.MULTIPLE_CHOICE, questionText: "_______ fine, thanks.", options: ["I am", "I", "I’m am", "I I’m"], correctAnswer: "I am", explanation: "I am fine: Tôi khỏe." },
  { id: 9, type: QuestionType.MULTIPLE_CHOICE, questionText: "Odd one out:", options: ["fish", "cat", "dog", "book"], correctAnswer: "book", explanation: "'Book' là đồ vật, các từ còn lại là con vật." },
  { id: 10, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["school.", "we", "This is", "go to", "the way"], correctAnswer: "This is the way we go to school.", explanation: "Đây là lối chúng em tới trường." },
  { id: 11, type: QuestionType.FILL_IN_BLANK, questionText: "Sit _ _ wn , please!", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-34.jpg"), correctAnswer: "do", explanation: "Sit down: Ngồi xuống." },
  { id: 12, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["she", "my", "he", "you"], correctAnswer: "my", explanation: "'My' là tính từ sở hữu, các từ còn lại là đại từ nhân xưng." },
  { id: 13, type: QuestionType.FILL_IN_BLANK, questionText: "How _ _ _ are you? – I’m seven years old.", correctAnswer: "old", explanation: "How old: Hỏi tuổi." },
  { id: 14, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["am fine", ", thanks.", "I", "you?", "And"], correctAnswer: "I am fine , thanks. And you?", explanation: "Tôi khỏe, cảm ơn. Còn bạn thì sao?" },
  { id: 15, type: QuestionType.MULTIPLE_CHOICE, questionText: "... are you? – I’m fine, thanks.", options: ["Hi", "Hello", "How", "How’s"], correctAnswer: "How", explanation: "How are you?: Bạn khỏe không?" },
  { id: 16, type: QuestionType.FILL_IN_BLANK, questionText: "CH_ SS", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-dt-45.jpg"), correctAnswer: "E", explanation: "CHESS: Cờ vua." },
  { id: 17, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["and", "My brother", "two dogs.", "has", "a cat"], correctAnswer: "My brother has a cat and two dogs.", explanation: "Anh tôi có một con mèo và hai con chó." },
  { id: 18, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["A", "in the classroom.", "is", "black board"], correctAnswer: "A black board is in the classroom.", explanation: "Có một cái bảng đen trong lớp học." },
  { id: 19, type: QuestionType.FILL_IN_BLANK, questionText: "These cats are _ _ _ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/22/635207308239844588_566X320.jpg"), correctAnswer: "black", explanation: "Màu đen (Black)." },
  { id: 20, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["new", "my", "teacher.", "is", "Miss Lien"], correctAnswer: "Miss Lien is my new teacher.", explanation: "Cô Liên là giáo viên mới của tôi." },
  { id: 21, type: QuestionType.FILL_IN_BLANK, questionText: "A: _ _ _ _ ’s it? - B: It’s my notebook.", correctAnswer: "What", explanation: "What's it?: Nó là cái gì?" },
  { id: 22, type: QuestionType.FILL_IN_BLANK, questionText: "Point _ _ the teacher.", correctAnswer: "to", explanation: "Point to: Chỉ vào." },
  { id: 23, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is your school new? - No. It's _____.", options: ["new", "old", "not", "is"], correctAnswer: "old", explanation: "Trái nghĩa với New (mới) là Old (cũ)." },
  { id: 24, type: QuestionType.MULTIPLE_CHOICE, questionText: "… that woman your new teacher?", options: ["Is", "Has", "Who’s", "Does"], correctAnswer: "Is", explanation: "Is that...: Đó có phải là..." },
  { id: 25, type: QuestionType.FILL_IN_BLANK, questionText: "Stand u_ , please.", correctAnswer: "p", explanation: "Stand up: Đứng dậy." },
  { id: 26, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is your classroom big? - …, it isn't. It’s small.", options: ["Yes", "Yes, it isn’t", "No, it is", "No"], correctAnswer: "No", explanation: "Câu trả lời phủ định ngắn gọn: No." },
  { id: 27, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["your", "to", "friend.", "Listen"], correctAnswer: "Listen to your friend.", explanation: "Lắng nghe bạn của bạn." },
  { id: 28, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’m ... , thank you. And you?", options: ["nice", "bye", "fine", "hi"], correctAnswer: "fine", explanation: "I'm fine: Tôi khỏe." },
  { id: 29, type: QuestionType.MULTIPLE_CHOICE, questionText: "… ? – It’s black.", options: ["What colour is it", "What is this", "How are you", "How many"], correctAnswer: "What colour is it", explanation: "Hỏi màu sắc: What colour is it?" },
  { id: 30, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Simon.", "Come", "over", "here,"], correctAnswer: "Come over here, Simon.", explanation: "Lại đây nào Simon." },
  { id: 31, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is this your ruler? - No, ____ isn't", options: ["it", "that", "its", "it's"], correctAnswer: "it", explanation: "No, it isn't." },
  { id: 32, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["the pink", "pen,", "please.", "Give", "me"], correctAnswer: "Give me the pink pen, please.", explanation: "Làm ơn đưa cho tôi cái bút màu hồng." },
  { id: 33, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: Who’s Tracy? - B: The girl is in the yellow shirt.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636505021981546006_566X320.jpg"), options: ["1", "2", "3", "4"], correctAnswer: "4", explanation: "Quan sát tranh: Cô gái mặc áo vàng là số 4." },
  { id: 34, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Don't", "girls!", "in class,", "talk"], correctAnswer: "Don't talk in class, girls!", explanation: "Đừng nói chuyện trong lớp, các cô gái!" },
  { id: 35, type: QuestionType.FILL_IN_BLANK, questionText: "Is it _ ruler? – No, it isn’t.", correctAnswer: "a", explanation: "A ruler: Một cái thước." },
  { id: 36, type: QuestionType.MULTIPLE_CHOICE, questionText: "Jack ___ in the playground.", options: ["are", "am", "is", "be"], correctAnswer: "is", explanation: "Jack (số ít) -> is." },
  { id: 37, type: QuestionType.MULTIPLE_CHOICE, questionText: "I go to school ___ my classmates.", options: ["in", "and", "but", "with"], correctAnswer: "with", explanation: "With: Cùng với." },
  { id: 38, type: QuestionType.FILL_IN_BLANK, questionText: "W_ _ t is this? – This is a marker.", correctAnswer: "ha", explanation: "What: Cái gì." },
  { id: 39, type: QuestionType.MULTIPLE_CHOICE, questionText: "May I go out? - ... .", options: ["Hello", "Nice to meet you", "Fine, thanks", "Sure"], correctAnswer: "Sure", explanation: "Sure: Chắc chắn rồi (cho phép)." },
  { id: 40, type: QuestionType.FILL_IN_BLANK, questionText: "That’s my fathe_ .", correctAnswer: "r", explanation: "Father: Bố." },
  { id: 41, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["that,", "Who's", "Peter?"], correctAnswer: "Who's that, Peter?", explanation: "Đó là ai vậy Peter?" },
  { id: 42, type: QuestionType.MULTIPLE_CHOICE, questionText: "I go to school library to ... books.", options: ["read’s", "reads", "read", "read to"], correctAnswer: "read", explanation: "To read: Để đọc." },
  { id: 43, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Are", "sick", "you", "today?"], correctAnswer: "Are you sick today?", explanation: "Hôm nay bạn bị ốm à?" },
  { id: 44, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["books", "How", "there?", "many", "are"], correctAnswer: "How many books are there?", explanation: "Có bao nhiêu quyển sách?" },
  { id: 45, type: QuestionType.MULTIPLE_CHOICE, questionText: "Hi, I’m Collin. Nice to meet ....", options: ["me", "they", "he", "you"], correctAnswer: "you", explanation: "Nice to meet you." },
  { id: 46, type: QuestionType.MULTIPLE_CHOICE, questionText: "... this a pencil?", options: ["Are", "You", "Is", "My"], correctAnswer: "Is", explanation: "Is this...?" },
  { id: 47, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’m standing in a ... .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206312811331111_Audio.mp3"), options: ["living room", "classroom", "room", "bedroom"], correctAnswer: "classroom", explanation: "Nghe audio: Lớp học." },
  { id: 48, type: QuestionType.FILL_IN_BLANK, questionText: "I like basketba_ _ .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/3-dt-36.mp3"), correctAnswer: "ll", explanation: "Basketball: Bóng rổ." },
  { id: 49, type: QuestionType.MULTIPLE_CHOICE, questionText: "The school _______ is large.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/3-tn-27.mp3"), options: ["gym", "school", "room", "library"], correctAnswer: "gym", explanation: "Nghe audio: Phòng tập thể dục." },
  { id: 50, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["the teacher", "Write", "what", "says."], correctAnswer: "Write what the teacher says.", explanation: "Viết những gì giáo viên nói." },
  { id: 51, type: QuestionType.FILL_IN_BLANK, questionText: "Unscramble this word: ’’YBEDOGO’’ -> ’’GOOD_ _ _ ’’.", correctAnswer: "BYE", explanation: "GOODBYE: Tạm biệt." },
  { id: 52, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: … that boy your friend? - B: Yes, ….", options: ["Are – they are", "Are – they aren’t", "Is – he isn’t", "Is – he is"], correctAnswer: "Is – he is", explanation: "That boy (số ít) -> Is. Yes, he is." },
  { id: 53, type: QuestionType.FILL_IN_BLANK, questionText: "My school _ _ new.", correctAnswer: "is", explanation: "My school (số ít) -> is." },
  { id: 54, type: QuestionType.MULTIPLE_CHOICE, questionText: "Odd one out:", options: ["fish", "cat", "dog", "book"], correctAnswer: "book", explanation: "'Book' là đồ vật." },
  { id: 55, type: QuestionType.FILL_IN_BLANK, questionText: "It’s a _ _ _ blue green ball.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161053165241455_Audio.mp3"), correctAnswer: "big", explanation: "Nghe audio: To lớn (big)." },
  { id: 56, type: QuestionType.MULTIPLE_CHOICE, questionText: "Lan and Hoa ___ in class 3C.", options: ["is", "am", "are", "on"], correctAnswer: "are", explanation: "Lan and Hoa (số nhiều) -> are." },
  { id: 57, type: QuestionType.FILL_IN_BLANK, questionText: "That is a blue s_ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208321994581633_566X320.jpg"), correctAnswer: "hip", explanation: "Ship: Tàu thủy." },
  { id: 58, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Let’s", "make", "a", "circle."], correctAnswer: "Let’s make a circle.", explanation: "Hãy tạo thành một vòng tròn." },
  { id: 59, type: QuestionType.FILL_IN_BLANK, questionText: "Put your books on the tabl_ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi%20Th%E1%BB%AD/Thi_trai_nghiem_2021/Lop3/images1/dt.jpg"), correctAnswer: "e", explanation: "Table: Cái bàn." },
  { id: 60, type: QuestionType.FILL_IN_BLANK, questionText: "My brother likes playing _ _ _ _ _ _ _ _ games.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/22/635207295518636244_566X320.jpg"), correctAnswer: "computer", explanation: "Computer games: Trò chơi điện tử." },
  { id: 61, type: QuestionType.MULTIPLE_CHOICE, questionText: "Goodbye. ...", options: ["Nice to meet you", "See you later", "Good morning", "Good evening"], correctAnswer: "See you later", explanation: "Chào tạm biệt -> Hẹn gặp lại sau." },
  { id: 62, type: QuestionType.FILL_IN_BLANK, questionText: "Our _ _ _ _ _ _ _ _ is not big.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/23/635208311247935975_566X320.jpg"), correctAnswer: "bathroom", explanation: "Bathroom: Phòng tắm (dựa vào hình ảnh nếu có, hoặc từ vựng phổ biến)." },
  { id: 63, type: QuestionType.MULTIPLE_CHOICE, questionText: "TA_LE", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/1-tn-40.jpg"), options: ["P", "B", "C", "G"], correctAnswer: "B", explanation: "TABLE: Cái bàn." },
  { id: 64, type: QuestionType.MULTIPLE_CHOICE, questionText: "Gale ______ books in the school library.", options: ["listens", "speaks", "says", "reads"], correctAnswer: "reads", explanation: "Reads books: Đọc sách." },
  { id: 65, type: QuestionType.MULTIPLE_CHOICE, questionText: "____ are his pets.", options: ["These", "This", "That", "It"], correctAnswer: "These", explanation: "Pets (số nhiều) -> These." },
  { id: 66, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["is", "name?", "your", "What", "mother's"], correctAnswer: "What is your mother's name?", explanation: "Tên mẹ bạn là gì?" },
  { id: 67, type: QuestionType.FILL_IN_BLANK, questionText: "Is this _ _ eraser?", correctAnswer: "an", explanation: "An eraser." },
  { id: 68, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["my", "friends.", "are", "These"], correctAnswer: "These are my friends.", explanation: "Đây là những người bạn của tôi." },
  { id: 69, type: QuestionType.MULTIPLE_CHOICE, questionText: "Put the books … the table.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/4/636506592106747089_Audio.mp3"), options: ["under", "on", "next to", "behind"], correctAnswer: "on", explanation: "Nghe audio: Ở trên (on)." },
  { id: 70, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is ... school bag.", options: ["he’s", "my’s", "me", "my"], correctAnswer: "my", explanation: "My (tính từ sở hữu)." },
  { id: 71, type: QuestionType.MULTIPLE_CHOICE, questionText: "The ball is ___ the box.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-tn-45.jpg"), options: ["in", "on", "at", "of"], correctAnswer: "in", explanation: "Nhìn tranh: Ở trong (in)." },
  { id: 72, type: QuestionType.MULTIPLE_CHOICE, questionText: "Listen and tick:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206308991508402_Audio.mp3"), options: ["This is my T-shirt.", "This is my shirt.", "This is my skirt.", "This is my jeans."], correctAnswer: "This is my T-shirt.", explanation: "Nghe audio." },
  { id: 73, type: QuestionType.MULTIPLE_CHOICE, questionText: "There is a picture … the wall.", options: ["in", "at", "on", "of"], correctAnswer: "on", explanation: "On the wall: Trên tường." },
  { id: 74, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is this a pencil box? – ..., it is.", options: ["No", "Not", "Yes", "No’s"], correctAnswer: "Yes", explanation: "Yes, it is." },
  { id: 75, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out", options: ["Green", "Yellow", "Apple", "Blue"], correctAnswer: "Apple", explanation: "'Apple' là trái cây, còn lại là màu sắc." },
  { id: 76, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["like", "My", "doesn’t", "brother", "cats."], correctAnswer: "My brother doesn’t like cats.", explanation: "Anh trai tôi không thích mèo." },
  { id: 77, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["school", "large?", "Is", "your"], correctAnswer: "Is your school large?", explanation: "Trường của bạn có rộng không?" },
  { id: 78, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the letter(s) to make a correct word: blac__", options: ["c", "t", "k", "h"], correctAnswer: "k", explanation: "BLACK: Màu đen." },
  { id: 79, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ do you spell your name, Sam? - It’s S-A-M.", correctAnswer: "How", explanation: "How do you spell...?" },
  { id: 80, type: QuestionType.FILL_IN_BLANK, questionText: "Listen and ti_ _ .", correctAnswer: "ck", explanation: "Tick: Đánh dấu." },
  { id: 81, type: QuestionType.FILL_IN_BLANK, questionText: "Let’s ma_ _ a line, students.", correctAnswer: "ke", explanation: "Make a line: Xếp hàng." },
  { id: 82, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["eight", "I", "am", "years old."], correctAnswer: "I am eight years old.", explanation: "Tôi 8 tuổi." },
  { id: 83, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["me.", "after", "repeat", "Please"], correctAnswer: "Please repeat after me.", explanation: "Làm ơn nhắc lại theo tôi." },
  { id: 84, type: QuestionType.FILL_IN_BLANK, questionText: "Bye. S_ _ you later.", correctAnswer: "ee", explanation: "See you later." },
  { id: 85, type: QuestionType.MULTIPLE_CHOICE, questionText: "My classroom is … .", options: ["name", "news", "new", "names"], correctAnswer: "new", explanation: "New (tính từ): Mới." },
  { id: 86, type: QuestionType.FILL_IN_BLANK, questionText: "Nice _ _ see you.", correctAnswer: "to", explanation: "Nice to see you." },
  { id: 87, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Put", "your", "down.", "hand"], correctAnswer: "Put your hand down.", explanation: "Hạ tay xuống." },
  { id: 88, type: QuestionType.MULTIPLE_CHOICE, questionText: "There are ... boats on the sea.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206364939134668_Audio.mp3"), options: ["twenty", "three", "two", "twelve"], correctAnswer: "three", explanation: "Nghe audio." },
  { id: 89, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["That", "green", "a", "is", "chair."], correctAnswer: "That is a green chair.", explanation: "Đó là một cái ghế màu xanh lá." },
  { id: 90, type: QuestionType.MULTIPLE_CHOICE, questionText: "What AREN’T the students doing?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636504878931926679_Audio.mp3"), options: ["Running", "Jumping", "Laughing", "Studying"], correctAnswer: "Studying", explanation: "Nghe audio: Họ đang chơi, không phải đang học." },
  { id: 91, type: QuestionType.FILL_IN_BLANK, questionText: "I’m fine, th_ _ k you.", correctAnswer: "an", explanation: "Thank you." },
  { id: 92, type: QuestionType.FILL_IN_BLANK, questionText: "There are two books o_ the table.", correctAnswer: "n", explanation: "On the table: Trên bàn." },
  { id: 93, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["on", "are there", "erasers", "How many", "the table?"], correctAnswer: "How many erasers are there on the table?", explanation: "Có bao nhiêu cục tẩy trên bàn?" },
  { id: 94, type: QuestionType.MULTIPLE_CHOICE, questionText: "My father is a doctor.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206377131960084_Audio.mp3"), options: ["My father is a teacher.", "My mother is a teacher", "My father is a doctor.", "My brother is a teacher."], correctAnswer: "My father is a doctor.", explanation: "Nghe audio." },
  { id: 95, type: QuestionType.MULTIPLE_CHOICE, questionText: "She wears a big ___ hat.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/4-tn-60.mp3"), options: ["black", "blue", "green", "yellow"], correctAnswer: "blue", explanation: "Nghe audio: Mũ xanh (blue)." },
  { id: 96, type: QuestionType.MULTIPLE_CHOICE, questionText: "This isn’t ... bag.", options: ["he", "his", "this", "he’s"], correctAnswer: "his", explanation: "His bag: Cặp của cậu ấy." },
  { id: 97, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’m fine, thank you. ... ?", options: ["You", "And you", "Are you", "Bye"], correctAnswer: "And you", explanation: "Hỏi ngược lại: Còn bạn thì sao?" },
  { id: 98, type: QuestionType.MULTIPLE_CHOICE, questionText: "Look! That flower is ....", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2015/12/3/635847534640208109_566X320.jpg"), options: ["pink", "blue", "green", "black"], correctAnswer: "blue", explanation: "Nhìn tranh: Hoa màu xanh (blue)." },
  { id: 99, type: QuestionType.FILL_IN_BLANK, questionText: "How _ _ you spell your name?", correctAnswer: "do", explanation: "How do you spell...?" },
  { id: 100, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Raise", "your", "hands,", "please"], correctAnswer: "Raise your hands, please", explanation: "Làm ơn giơ tay lên." },
  { id: 101, type: QuestionType.MULTIPLE_CHOICE, questionText: "There are … sweets.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161037811773395_Audio.mp3"), options: ["three", "two", "four", "no"], correctAnswer: "two", explanation: "Nghe audio: 2 cái kẹo." },
  { id: 102, type: QuestionType.FILL_IN_BLANK, questionText: "Point and s_ y.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/4-dt-38.mp3"), correctAnswer: "a", explanation: "Say: Nói." },
  { id: 103, type: QuestionType.MULTIPLE_CHOICE, questionText: "... your name?", options: ["What", "What’s", "How’s", "Why’s"], correctAnswer: "What’s", explanation: "What's your name?" },
  { id: 104, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Hi, Mary.", "Nice to meet you."], correctAnswer: "Hi, Mary. Nice to meet you.", explanation: "Chào Mary. Rất vui được gặp bạn." },
  { id: 105, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["you", "I", "she", "my"], correctAnswer: "my", explanation: "'My' là tính từ sở hữu, còn lại là đại từ nhân xưng." },
  { id: 106, type: QuestionType.FILL_IN_BLANK, questionText: "I’m fine, th_ _ _ k you.", correctAnswer: "an", explanation: "Thank you." },
  { id: 107, type: QuestionType.MULTIPLE_CHOICE, questionText: "I ... Maths and Arts on Monday.", options: ["play", "say", "study", "look"], correctAnswer: "study", explanation: "Study: Học." },
  { id: 108, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["My rubber is small", "and my ruler is short."], correctAnswer: "My rubber is small and my ruler is short.", explanation: "Cục tẩy của tôi nhỏ và thước kẻ của tôi ngắn." },
  { id: 109, type: QuestionType.MULTIPLE_CHOICE, questionText: "I’m fine, thank ... .", options: ["yous", "you’s", "you’re", "you"], correctAnswer: "you", explanation: "Thank you." },
  { id: 110, type: QuestionType.FILL_IN_BLANK, questionText: "Sit do_ n, please.", correctAnswer: "w", explanation: "Sit down." },
  { id: 111, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Jenny is my friend."], correctAnswer: "Jenny is my friend.", explanation: "Jenny là bạn của tôi." },
  { id: 112, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["May I borrow your notebook?"], correctAnswer: "May I borrow your notebook?", explanation: "Tôi có thể mượn vở của bạn không?" },
  { id: 113, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Where are your books?"], correctAnswer: "Where are your books?", explanation: "Sách của bạn ở đâu?" },
  { id: 114, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["This is a purple bag."], correctAnswer: "This is a purple bag.", explanation: "Đây là một cái cặp màu tím." },
  { id: 115, type: QuestionType.MULTIPLE_CHOICE, questionText: "Where are ... from?", options: ["and", "my", "you", "she"], correctAnswer: "you", explanation: "Where are you from?" },
  { id: 116, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["How are you today, Mai and Phong?"], correctAnswer: "How are you today, Mai and Phong?", explanation: "Hôm nay các bạn thế nào, Mai và Phong?" },
  { id: 117, type: QuestionType.FILL_IN_BLANK, questionText: "Bye. _ _ _ you later.", correctAnswer: "see", explanation: "See you later." },
  { id: 118, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Please", "repeat", "after", "me."], correctAnswer: "Please repeat after me.", explanation: "Làm ơn nhắc lại theo tôi." },
  { id: 119, type: QuestionType.MULTIPLE_CHOICE, questionText: "A: What colour is this? - B: It’s ... .", options: ["book", "a green", "green", "pencil"], correctAnswer: "green", explanation: "Trả lời màu sắc: It's green." },
  { id: 120, type: QuestionType.MULTIPLE_CHOICE, questionText: "Open ... book, please.", options: ["you", "your", "you’s", "your’s"], correctAnswer: "your", explanation: "Your book." },
  { id: 121, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ this a ruler? – Yes, it is.", correctAnswer: "Is", explanation: "Is this...?" },
  { id: 122, type: QuestionType.FILL_IN_BLANK, questionText: "Listen _ _ me, please.", correctAnswer: "to", explanation: "Listen to me." },
  { id: 123, type: QuestionType.FILL_IN_BLANK, questionText: "That is my ho_ _ e.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/22/635207345145450116_566X320.jpg"), correctAnswer: "us", explanation: "House: Ngôi nhà." },
  { id: 124, type: QuestionType.MULTIPLE_CHOICE, questionText: "Nam's pencils are_____ .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/2-tn-23.mp3"), options: ["black", "blue", "green", "red"], correctAnswer: "green", explanation: "Nghe audio: Màu xanh lá." },
  { id: 125, type: QuestionType.MULTIPLE_CHOICE, questionText: "Where is the ...?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206313406004155_Audio.mp3"), options: ["bus", "class", "lab", "tab"], correctAnswer: "lab", explanation: "Nghe audio: Phòng thí nghiệm (lab)." },
  { id: 126, type: QuestionType.FILL_IN_BLANK, questionText: "E_ GHT", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/2-dt-41.jpg"), correctAnswer: "I", explanation: "EIGHT: Số 8." },
  { id: 127, type: QuestionType.MULTIPLE_CHOICE, questionText: "How do you … your name? – That’s A-N-N-E.", options: ["spell", "read", "call", "say"], correctAnswer: "spell", explanation: "Spell: Đánh vần." },
  { id: 128, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Raise", "your", "hand."], correctAnswer: "Raise your hand.", explanation: "Giơ tay lên." },
  { id: 129, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out", options: ["Ruler", "Pen", "Book", "Library"], correctAnswer: "Library", explanation: "'Library' là địa điểm, còn lại là dụng cụ học tập." },
  { id: 130, type: QuestionType.FILL_IN_BLANK, questionText: "LIS_ EN", correctAnswer: "T", explanation: "LISTEN: Nghe." },
  { id: 131, type: QuestionType.FILL_IN_BLANK, questionText: "Nam’s pencil is _ _ _ _ but mine is short.", correctAnswer: "long", explanation: "Long: Dài (trái nghĩa với short)." },
  { id: 132, type: QuestionType.FILL_IN_BLANK, questionText: "Gi_ e me the book, please.", correctAnswer: "v", explanation: "Give: Đưa." },
  { id: 133, type: QuestionType.FILL_IN_BLANK, questionText: "My n_ me is Hieu.", correctAnswer: "a", explanation: "Name: Tên." },
  { id: 134, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ _ the bag, please.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/22/635207366284327721_566X320.jpg"), correctAnswer: "Open", explanation: "Open the bag: Mở cặp." },
  { id: 135, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["I don't", "go to", "school", "today."], correctAnswer: "I don't go to school today.", explanation: "Hôm nay tôi không đi học." },
  { id: 136, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Listen to", "the", "teacher."], correctAnswer: "Listen to the teacher.", explanation: "Lắng nghe giáo viên." },
  { id: 137, type: QuestionType.MULTIPLE_CHOICE, questionText: "This isn’t ... ruler. It’s my ruler.", options: ["he’s", "his", "me’s", "you’s"], correctAnswer: "his", explanation: "His ruler: Thước của cậu ấy." },
  { id: 138, type: QuestionType.FILL_IN_BLANK, questionText: "Mary is at sch_ _ l.", correctAnswer: "oo", explanation: "School: Trường học." },
  { id: 139, type: QuestionType.FILL_IN_BLANK, questionText: "David and Tony p_ _ _ football after school.", correctAnswer: "lay", explanation: "Play football: Chơi bóng đá." },
  { id: 140, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["My", "shoes", "are", "new", "pink."], correctAnswer: "My new shoes are pink.", explanation: "Đôi giày mới của tôi màu hồng." },
  { id: 141, type: QuestionType.FILL_IN_BLANK, questionText: "Gi_ e me a pen, please.", correctAnswer: "v", explanation: "Give: Đưa." },
  { id: 142, type: QuestionType.FILL_IN_BLANK, questionText: "St_ _ d up, please.", correctAnswer: "an", explanation: "Stand up: Đứng dậy." },
  { id: 143, type: QuestionType.FILL_IN_BLANK, questionText: "Is th_ _ _ any water in the fridge, mom?", correctAnswer: "ere", explanation: "Is there...?" },
  { id: 144, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ many students are there in your classroom?", correctAnswer: "How", explanation: "How many." },
  { id: 145, type: QuestionType.MULTIPLE_CHOICE, questionText: "…, students. See you tomorrow.", options: ["Good morning", "Good night", "Goodbye", "Nice to meet you"], correctAnswer: "Goodbye", explanation: "See you tomorrow -> Goodbye." },
  { id: 146, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Don't", "ride", "your", "bike", "too fast."], correctAnswer: "Don't ride your bike too fast.", explanation: "Đừng đạp xe quá nhanh." },
  { id: 147, type: QuestionType.FILL_IN_BLANK, questionText: "She is my tea_ _ er.", correctAnswer: "ch", explanation: "Teacher: Giáo viên." },
  { id: 148, type: QuestionType.FILL_IN_BLANK, questionText: "M_ THER", correctAnswer: "O", explanation: "MOTHER: Mẹ." },
  { id: 149, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["How many", "books", "are there", "in", "your school bag?"], correctAnswer: "How many books are there in your school bag?", explanation: "Có bao nhiêu quyển sách trong cặp của bạn?" },
  { id: 150, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Put", "your pencil", "down."], correctAnswer: "Put your pencil down.", explanation: "Đặt bút xuống." },
  { id: 151, type: QuestionType.FILL_IN_BLANK, questionText: "Does she have bl_ _ _ _ hair?", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/16/636174959719066879_566X320.jpg"), correctAnswer: "onde", explanation: "Blonde hair: Tóc vàng." },
  { id: 152, type: QuestionType.FILL_IN_BLANK, questionText: "Pl_ _ _ ed to meet you, Linda.", correctAnswer: "eas", explanation: "Pleased to meet you." },
  { id: 153, type: QuestionType.MULTIPLE_CHOICE, questionText: "My school .... is small.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636505008466109219_566X320.jpg"), options: ["playground", "library", "classroom", "gym"], correctAnswer: "playground", explanation: "Nhìn tranh: Sân chơi (playground)." },
  { id: 154, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ _ _ are my crayons.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2018/1/2/636504891760936521_Audio.mp3"), correctAnswer: "Those", explanation: "Nghe audio: Kia là (Those)." },
  { id: 155, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Does", "she like", "volleyball", "or", "basketball?"], correctAnswer: "Does she like volleyball or basketball?", explanation: "Cô ấy thích bóng chuyền hay bóng rổ?" },
  { id: 156, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is ... cat.", options: ["he", "she", "my", "you"], correctAnswer: "my", explanation: "My cat: Mèo của tôi." },
  { id: 157, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["eraser", "ruler", "name", "pen"], correctAnswer: "name", explanation: "'Name' là danh từ trừu tượng, còn lại là đồ vật." },
  { id: 158, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Would", "you", "like", "an", "ice cream?"], correctAnswer: "Would you like an ice cream?", explanation: "Bạn có muốn ăn kem không?" },
  { id: 159, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ _ , he is.", correctAnswer: "Yes", explanation: "Yes, he is." },
  { id: 160, type: QuestionType.FILL_IN_BLANK, questionText: "My brother likes to play computer g_ _ _ _ .", correctAnswer: "ames", explanation: "Games: Trò chơi." },
  { id: 161, type: QuestionType.MULTIPLE_CHOICE, questionText: "Two maps __ on the wall.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/4-tn-56.jpg"), options: ["are", "is", "re", "am"], correctAnswer: "are", explanation: "Two maps (số nhiều) -> are." },
  { id: 162, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["how", "hello", "hi", "good morning"], correctAnswer: "how", explanation: "'How' là từ để hỏi, còn lại là lời chào." },
  { id: 163, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["book", "pencil", "rubber", "library"], correctAnswer: "library", explanation: "'Library' là địa điểm, còn lại là đồ dùng." },
  { id: 164, type: QuestionType.FILL_IN_BLANK, questionText: "This is my _ _ _ .", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/11/30/636161052058989367_Audio.mp3"), correctAnswer: "hat", explanation: "Nghe audio (hoặc đoán từ): Hat (mũ)." },
  { id: 165, type: QuestionType.FILL_IN_BLANK, questionText: "W_ _ _ are these? – These are pencil cases.", correctAnswer: "hat", explanation: "What are these?" },
  { id: 166, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the odd one out:", options: ["young", "white", "pink", "gray"], correctAnswer: "young", explanation: "'Young' là tính từ chỉ tuổi/tính chất, còn lại là màu sắc." },
  { id: 167, type: QuestionType.FILL_IN_BLANK, questionText: "Come here and _ _ _ _ an English song now.", correctAnswer: "sing", explanation: "Sing a song: Hát." },
  { id: 168, type: QuestionType.FILL_IN_BLANK, questionText: "Don't talk _ _ class!", correctAnswer: "in", explanation: "In class: Trong lớp." },
  { id: 169, type: QuestionType.FILL_IN_BLANK, questionText: "Fine, th_ nks.", correctAnswer: "a", explanation: "Thanks." },
  { id: 170, type: QuestionType.FILL_IN_BLANK, questionText: "Choose the letter(s) to make a correct word: pencil c__se", options: ["a", "e", "i", "o"], correctAnswer: "a", explanation: "Pencil case: Hộp bút." },
  { id: 171, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Look", "at", "the", "board."], correctAnswer: "Look at the board.", explanation: "Nhìn lên bảng." },
  { id: 172, type: QuestionType.FILL_IN_BLANK, questionText: "A: Who’s that boy? - B: _ _ ’s Peter.", correctAnswer: "He", explanation: "He is Peter." },
  { id: 173, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["The window", "is", "new,", "too."], correctAnswer: "The window is new, too.", explanation: "Cửa sổ cũng mới." },
  { id: 174, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the incorrect word(s) in the following sentence: Do you like hide seek?", options: ["Do", "you", "like", "hide seek"], correctAnswer: "hide seek", explanation: "Sai: phải là 'hide and seek'." },
  { id: 175, type: QuestionType.FILL_IN_BLANK, questionText: "Unscramble this word: ’’HOLOCS’’ -> ’’SCHO_ _ ’’.", correctAnswer: "OL", explanation: "SCHOOL: Trường học." },
  { id: 176, type: QuestionType.MULTIPLE_CHOICE, questionText: "Is this ___ bike? - No, it isn't.", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi%20Th%E1%BB%AD/Thi_trai_nghiem_2021/Lop3/tracnghiem/tn-62.mp3"), options: ["his", "your", "my", "her"], correctAnswer: "your", explanation: "Nghe audio: Your bike." },
  { id: 177, type: QuestionType.MULTIPLE_CHOICE, questionText: "My bag is ______.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/1-tn-64.jpg"), options: ["blue", "gray", "black", "yellow"], correctAnswer: "blue", explanation: "Nhìn tranh: Màu xanh dương (blue)." },
  { id: 178, type: QuestionType.MULTIPLE_CHOICE, questionText: "Choose the sentence that you hear:", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2019/11/29/637106243647920057_Audio.mp3"), options: ["I’m fine.", "I’m fine, thanks.", "Fine, thank you.", "I am fine, thank you."], correctAnswer: "Fine, thank you.", explanation: "Nghe audio." },
  { id: 179, type: QuestionType.FILL_IN_BLANK, questionText: "How are y_ _ ?", correctAnswer: "ou", explanation: "How are you?" },
  { id: 180, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["This", "is", "my", "pet."], correctAnswer: "This is my pet.", explanation: "Đây là thú cưng của tôi." },
  { id: 181, type: QuestionType.FILL_IN_BLANK, questionText: "Sally has bl_ _ eyes and blonde hair.", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2016/12/1/636174948921681281_566X320.jpg"), correctAnswer: "ue", explanation: "Blue eyes: Mắt xanh." },
  { id: 182, type: QuestionType.MULTIPLE_CHOICE, questionText: "Odd one out:", options: ["meet", "I", "you", "he"], correctAnswer: "meet", explanation: "'Meet' là động từ, còn lại là đại từ." },
  { id: 183, type: QuestionType.FILL_IN_BLANK, questionText: "It's a brow_ teddy bear.", correctAnswer: "n", explanation: "Brown: Màu nâu." },
  { id: 184, type: QuestionType.FILL_IN_BLANK, questionText: "Horses and sheep live on the _ _ _ _ .", correctAnswer: "farm", explanation: "Farm: Nông trại." },
  { id: 185, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Let’s", "read", "the", "book."], correctAnswer: "Let’s read the book.", explanation: "Hãy đọc sách nào." },
  { id: 186, type: QuestionType.FILL_IN_BLANK, questionText: "Tha_ is my doll.", correctAnswer: "t", explanation: "That: Kia/Đó." },
  { id: 187, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["Stand up", "and", "open", "your book."], correctAnswer: "Stand up and open your book.", explanation: "Đứng dậy và mở sách ra." },
  { id: 188, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["My school", "isn’t big", "but", "very tidy."], correctAnswer: "My school isn’t big but very tidy.", explanation: "Trường tôi không lớn nhưng rất gọn gàng." },
  { id: 189, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["I", "want to", "travel", "around", "the world."], correctAnswer: "I want to travel around the world.", explanation: "Tôi muốn đi du lịch vòng quanh thế giới." },
  { id: 190, type: QuestionType.FILL_IN_BLANK, questionText: "It _ _ a pencil.", correctAnswer: "is", explanation: "It is." },
  { id: 191, type: QuestionType.FILL_IN_BLANK, questionText: "List_ _ carefully.", correctAnswer: "en", explanation: "Listen: Nghe." },
  { id: 192, type: QuestionType.FILL_IN_BLANK, questionText: "SCHOOL-B_ G", correctAnswer: "A", explanation: "SCHOOL-BAG: Cặp sách." },
  { id: 193, type: QuestionType.MULTIPLE_CHOICE, questionText: "This is my ... .", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/ImageExam/2013/11/21/635206312195910030_Audio.mp3"), options: ["class", "school", "room", "desk"], correctAnswer: "school", explanation: "Nghe audio: Trường học." },
  { id: 194, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["I am", "a pupil", "at", "Quang Trung Primary School."], correctAnswer: "I am a pupil at Quang Trung Primary School.", explanation: "Tôi là học sinh trường tiểu học Quang Trung." },
  { id: 195, type: QuestionType.MULTIPLE_CHOICE, questionText: "What does he do during ... lessons? - He learns about numbers.", options: ["Maths", "English", "Arts", "Music"], correctAnswer: "Maths", explanation: "Numbers (số) -> Maths (Toán)." },
  { id: 196, type: QuestionType.FILL_IN_BLANK, questionText: "We write \"06:20\" and we say \"It’s twenty _ _ _ _ six\".", correctAnswer: "past", explanation: "20 past 6 (6 giờ 20)." },
  { id: 197, type: QuestionType.MULTIPLE_CHOICE, questionText: "What colour is ______?", audioUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Audio/3-tn-59.mp3"), options: ["they", "that", "it", "these"], correctAnswer: "it", explanation: "Nghe audio: Số ít (is) -> it." },
  { id: 198, type: QuestionType.FILL_IN_BLANK, questionText: "_ _ OWN SHOES", imageUrl: cleanUrl("https://res.ioe.vn/edu/EOlympic/ExamData/Thi_cac_cap/2020-2021/Lop3/Captruong/Images/3-dt-15.jpg"), correctAnswer: "BR", explanation: "BROWN: Màu nâu." },
  { id: 199, type: QuestionType.FILL_IN_BLANK, questionText: "That is my fa_ _ er.", correctAnswer: "th", explanation: "Father: Bố." },
  { id: 200, type: QuestionType.REARRANGE, questionText: "Sắp xếp câu:", rearrangeParts: ["It's", "a", "nice", "puppy."], correctAnswer: "It's a nice puppy.", explanation: "Đó là một chú cún dễ thương." }
];